# Generated by Django 5.2.6 on 2025-09-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code_upc',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
