# Generated by Django 5.2.6 on 2025-09-14 00:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomi', '0002_alter_student_code_upc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ticket', models.CharField(max_length=20, unique=True)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type_ticket', models.CharField(choices=[('Problemas de comunicación', 'Problemas de comunicación'), ('Errores en el formulario', 'Errores en el formulario'), ('Documentación incompleta', 'Documentación incompleta')], default='other', max_length=50)),
                ('state', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('resolved', 'Resuelto'), ('closed', 'Cerrado')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Baja', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('atendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pomi.admin')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pomi.whatsappuserstudent')),
            ],
        ),
    ]
