# Generated by Django 5.2.6 on 2025-09-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomi', '0003_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='respuesta_actual',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='respuesta_anterior',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
