# Generated by Django 5.2.6 on 2025-09-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomi', '0004_ticket_respuesta_actual_ticket_respuesta_anterior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='respuesta_actual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='respuesta_anterior',
            field=models.TextField(blank=True, null=True),
        ),
    ]
