# Generated by Django 5.2.1 on 2025-09-16 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomi', '0005_alter_ticket_respuesta_actual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackGPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_conversación', models.CharField(max_length=20, unique=True)),
                ('pregunta', models.CharField(max_length=300)),
                ('respuesta', models.CharField(max_length=400)),
                ('tiempo', models.CharField(max_length=10)),
                ('whatsAppStudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pomi.whatsappuserstudent')),
            ],
        ),
    ]
