# Generated by Django 5.2.6 on 2025-09-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomi', '0006_feedbackgpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackgpt',
            name='tiempo',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
