# Generated by Django 5.2.6 on 2025-11-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomi', '0007_alter_feedbackgpt_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappuserstudent',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
